config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_message
    @message = Message.find(params[:message_id])
  end

  def find_comment
    @comment = @message.comments.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:title, :description)
  end

  def find_message
    @message = Message.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted by <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

<% if user_signed_in? %>
  <% if comment.user_id == current_user.id %>
    <%= link_to "Edit", edit_message_comment_path(comment.message, comment), class: "btn btn-info" %>
    <%= link_to "Delete", message_comment_path(comment.message, comment), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "New Message ", new_message_path, class: "nav-link btn btn-outline-primary" %>
      </li>
      <li class="nav-item">

      </li>
      <li class="nav-item">
        <%= link_to "Sign Out ", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login ", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">

      </li>
      <li class="nav-item">
        <%= link_to "Sign Up ", new_user_registration_path, class: "nav-link" %>
      </li>
      <% end %>

    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messageboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message title" %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/messages/edit.html.erb
<h3>Edit Message</h3>

<%= render 'form' %>

app/views/messages/index.html.erb
<h1>This is the index view</h1>
<% @messages.each do |message| %>
  <h3><%= message.title %></h3>
  <%= link_to "Show", message_path(message), class: "btn btn-primary" %>
<% end %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<h2><%= @message.title %></h3>
<p>Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
<p><%= @message.description %></p>

<hr>

<h4>Comments: </h4>
<%= render @message.comments %>

<hr>

<h4>Reply to Message: </h4>
<%= render 'comments/form' %>

<%= link_to "Back", root_path, class: "btn btn-primary" %>
<% if user_signed_in? %>
  <% if @message.user_id == current_user.id %>
    <%= link_to "Edit", edit_message_path(@message), class: "btn btn-primary" %>
    <%= link_to "Delete", message_path(@message), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger"  %>
  <% end %>
<% end %>